const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94756966083"
const SESSION_ID = "PRABATH-MD~WcdnUTrR#0_xqZ2S4hjPVmvPUZzEphLotETHC8Cy5l-M0e_d4JUs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
